import { Header } from "@/ui/layout/Header";
import type { Metadata } from "next";
import { YakThemeProvider } from "next-yak";
import { Geist, Geist_Mono } from "next/font/google";
import { ToastContainer } from 'react-toastify';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <YakThemeProvider>
      <html lang="es" data-theme="dim2">
        <body
          className={`${geistSans.variable} ${geistMono.variable} bg-base-100 text-base-content`}
        >
          <Header />
          {children}
          <ToastContainer />
        </body>
      </html>
    </YakThemeProvider>
  );
}
